# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/CareerSite
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: unit-tests
          command: npm run test
  stage:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push to Harbor Registry for vulnerability scan and backup
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin
            docker build -t chaseweyer/careersite:${CIRCLE_SHA1} .
            docker push chaseweyer/careersite:${CIRCLE_SHA1}
  deploy:
    docker:
      - image: cimg/base:2020.01
        # auth:
        #   username: $HARBOR_USERNAME
        #   password: $HARBOR_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to Heroku Container Registry and Deploy as Application
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            docker build --rm=false -t registry.heroku.com/$HEROKU_APP_NAME/web .
            echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            cat <<EOT >> ~/.netrc
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            EOT
            heroku container:release -a $HEROKU_APP_NAME web
workflows:
  version: 2
  build-stage-deploy:
    jobs:
      - build
      - stage:
          requires:
            - build
      - deploy:
          requires:
            - build
            - stage
          filters:
            branches:
              only: master
