# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/CareerSite
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: unit-tests
          command: npm run test
  stage:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push to Harbor Registry for vulnerability scan and backup
          command: |
            docker build -t registry.chaseweyer.com/webapp/careersite:${CIRCLE_SHA1} .
            echo "$HARBOR_PASSWORD" | docker login --username=$HARBOR_USERNAME --password-stdin registry.chaseweyer.com
            docker push registry.chaseweyer.com/webapp/careersite:${CIRCLE_SHA1}
  deploy:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to Heroku Container Registry and Deploy as Application
          command: |
            docker build --rm=false -t registry.heroku.com/$HEROKU_APP_NAME/web .
            echo "$HEROKU_API_KEY" | docker login --username=$HEROKU_LOGIN --password-stdin registry.heroku.com
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
workflows:
  version: 2
  build-stage-deploy:
    jobs:
      - build
      - stage:
          requires:
            - build
      - deploy:
          requires:
            - build
            - stage
          filters:
            branches:
              only: master
