# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: registry.chaseweyer.com/devtools/nodejs:10.16.3-100
        auth:
          username: $HARBOR_USERNAME
          password: $HARBOR_PASSWORD

    working_directory: ~/CareerSite

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: npm install
          
      - run:
          name: unit-tests
          command: npm run test

      - save_cache:
          name: save-node-modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          name: save-dist
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist
  stage:
    docker:
      - image: registry.chaseweyer.com/devtools/nodejs:10.16.3-100
        auth:
          username: $HARBOR_USERNAME
          password: $HARBOR_PASSWORD
      steps:
        - checkout
        - setup_remote_docker
        - run:
          name: Push to Harbor Registry for vulnerability scan and backup
          command: |
            docker build -t registry.chaseweyer.com/webapp/careersite:${CIRCLE_SHA1} .
            echo "$HARBOR_PASSWORD" | docker login --username=$HARBOR_USERNAME --password-stdin
            docker push registry.chaseweyer.com/webapp/careersite:${CIRCLE_SHA1}
  deploy:
    docker:
      - image: registry.chaseweyer.com/devtools/heroku-cli:7.33.1-100
    steps:
      - checkout
      - run:
          name: Deploy to Heroku Container Registry and Deploy as Application
          command: |
            docker build --rm=false -t registry.heroku.com/afternoon-eyrie-76088/web .
            echo "$HEROKU_API_KEY" | docker login --username=$HEROKU_LOGIN --password-stdin
            docker push registry.heroku.com/afternoon-eyrie-76088/web

workflows:
  version: 2
  build-stage-deploy:
    jobs:
      - build
      - stage:
          requires:
            - build
      - deploy:
          requires:
            - build
            - stage
          filters:
            branches:
              only: master
