# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/CareerSite
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      # - run:
      #     name: unit-tests
      #     command: npm run test
  stage:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - run:
          name: Build Angular Website and Deploy it to Dev
          command: npm install
      - aws-s3/sync:
          from: dist/CareerSite
          to: s3://${DEV_BUCKET}
  deploy:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - run:
          name: Build Angular Website and deploy it to Prod
          command: npm install
      - aws-s3/sync:
          from: dist/CareerSite
          to: s3://${PROD_BUCKET}
workflows:
  version: 2
  build-stage-deploy:
    jobs:
      - build
      - stage:
          requires:
            - build
      - deploy:
          type: approval
          requires:
            - build
            - stage
          filters:
            branches:
              only: master
